title: Kevin Berry
safe:        false
base-url:    /
permalink:   none
markdown: redcarpet
highlighter: rouge
description: My personal website, to showcase my work and organize all of web content into one place.


source:      .
destination: _site
plugins_dir: _plugins
sass:
  sass_dir: _sass

gems:
  - jekyll-compass
  - rouge
  - jekyll-last-modified-at