title: Kevin Berry
email: hello@kevin-berry.com
twitter_username: lostmarinero
github_username:  lostmarinero
safe:        false
base-url:    ""
url: "http://kevin-berry.com"
permalink:   none
highlighter: rouge
description: The personal website of Kevin Berry, a ruby and python focused developer.


source: src
destination: public
plugins_dir: _plugins
sass:
  sass_dir: _sass
  style: compressed


# Build settings
markdown: kramdown
gems:
  - rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
